linters:
  disable-all: true
  enable:
  - errcheck
  - gosimple
  - govet
  - gofmt
  - gci
  - revive
  - ineffassign
  - staticcheck
  - misspell
  - gocyclo
  - typecheck
  - megacheck
  - goimports
  - goconst
  - unconvert
  - gocritic
issues:
  exclude-rules:
  - path: example.*_test\.go
    linters:
    - ineffassign
    - revive
  exclude-use-default: false
