---
resources:
- name: osspi-tool
  type: git
  icon: gitlab
  source:
    uri: git@gitlab.eng.vmware.com:source-insight-tooling/norsk-to-osspi.git
    private_key: ((tas2to.norsk-to-osspi-private-key))
    branch: main
- name: wavefront-sdk-go
  type: git
  source:
    uri: git@github.com:wavefrontHQ/wavefront-sdk-go
    branch: main
    private_key: ((tas2to.github-private-key))

jobs:
- name: wavefront-sdk-go-scan
  serial: true
  plan:
  - in_parallel:
    - get: osspi-tool
    - get: wavefront-sdk-go
      trigger: true
      params: { submodules: all }
  - in_parallel:
    - task: osspi-scan-wavefront-sdk-go
      file: osspi-tool/tasks/osspi/run-osspi-source.yaml
      input_mapping:
        repo1: osspi-tool
        repo2: wavefront-sdk-go
      params:
        REPO: repo2
        OSM_ENVIRONMENT: ((osm-environment))
        API_KEY: ((tas2to.apikey-((osm-environment))))
        USERNAME: ((tas2to.user-((osm-environment))))
        PRODUCT: wavefront-sdk-go
        VERSION: ((version))
        OSM_PACKAGE_GROUP_NAME: wavefront-sdk-go
        PREPARE: |
          go mod vendor
        OSSPI_SCANNING_PARAMS: |
          enable: true
          include_bomtools: "go_mod"
          search_depth: 5
          go_mod.path: "/go/bin/go"
        OSSPI_IGNORE_RULES: |
          - name_regex: stretchr/testify
            version_regex: .*
