name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  run_suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.19.x, 1.20.x, 1.21.x]
    name: Go ${{ matrix.go-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
      - run: go test -timeout 10m -v -race ./...
      - run: go vet ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
