name: post-release

on:
  release:
    types: [ published ]

jobs:
  pkg-go-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - run: RELEASE_VERSION="$(echo "$GITHUB_REF" | sed 's/refs\/tags\///')" ./scripts/add-release-to-pkg-go-dev.sh
