name: post-release

on:
  release:
    types: [ published ]

jobs:
  pkg-go-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
    - run: RELEASE_VERSION="$GITHUB_REF" ./scripts/add-release-to-pkg-go-dev.sh
